feat(footer): add external links and logos
fi-ksi/web-frontend-angular pull request #71
Opened 2022-10-09 18:24 UTC by danyroza

fixes #64

2022-10-09 19:16 UTC, esoadamo commented
Díky za implementaci, rád zase vidím ikonky! (A teď ještě i s animacemi po najetí šipkou!)
Napadlo mě pár menších úprav:
- `h3.links-title` mi přijde nadbytečné, úplně bych ten nadpis `Odkazy` odstranil
- na mobilu to má perfektní velikost, ale možná to na PC zmenšit, aby to bylo kompaktnější? Co třeba 2.5rem?
- na padding a margin prosím používej [existující proměnné](https://github.com/fi-ksi/web-frontend-angular/blob/main/src/app/styles/vars.scss#L6), pomáhá to jednotnému stylu
- moc se mi nezdá, že odkazy jsou zarovnány doprostřed a střed doleva, asi by to chtělo sjednotit

Co myslíš?

2022-10-10 07:27 UTC, esoadamo requested changes
Viz předchozí komentář

2022-10-10 19:46 UTC, danyroza commented
- Title smazán
- ikonky zmenšeny na 3 (i to mi přijde dost málo, zase aby to bylo trošku čitelné)
- proměnné použity
- margin jsem nyní aplikoval na odkazy, nikoliv na fotky (viz screenshot)

![image](https://user-images.githubusercontent.com/25553099/194941562-d0431222-8f76-4750-b7a5-44b4ae35a080.png)

2022-10-11 17:04 UTC, esoadamo approved these changes

2022-10-11 17:04 UTC, merged