fix: date timezone offset
fi-ksi/web-frontend-angular pull request #73
Opened 2022-10-12 18:27 UTC by danyroza

fixes #59

2022-10-13 09:09 UTC, esoadamo requested changes
Díky moc za implementaci! Mohl bys prosím mrknout, jestli by to šlo upravit trochu tak, že bychom nepřišli o možnost předávat, jak má výsledek vypadat? Jakože jestli má být formát short/long atp.

2022-10-13 09:09 UTC, esoadamo commented on src/app/pipes/shared/ksi-date.pipe.ts
> +    return new Date(correctTime).toLocaleString();
Myslíš, že by to šlo upravit tak, že to to správné datum pošle spolu s předanými parametry originální date pipe? Díky tomu bychom mohli použít všechny možnosti Angulaří date pipe

2022-10-14 21:43 UTC, danyroza commented
Mělo by to fungovat, bohužel jsem omezen testovacím prostředím a nejsem schopen přesně říct, jestli je ten nový čas opravdu správně => prosím o otestování.

Další věc je, že netuším, kde všude budeme chtít "medium" verzi toho datumu, tedy datum + čas místo samotného datumu.

2022-10-15 15:23 UTC, esoadamo requested changes
Funguje to krásně, díky moc! :heart_eyes: 
Jenom se dívám, že se změnilo pár formátů - je to zamýšlená změna?
+ jedna malá poznámka k `any`

2022-10-15 15:23 UTC, esoadamo commented on src/app/components/shared/discussion-thread/discussion-thread-posts/discussion-thread-posts.component.html
> +    {{post.published_at | ksiDate:'medium'}}
```suggestion
    {{post.published_at | ksiDate:'short'}}
```

2022-10-15 15:23 UTC, esoadamo commented on src/app/components/shared/article-preview/article-preview.component.html
> +<span class="date">{{article.time_published | ksiDate }}</span>
```suggestion
<span class="date">{{article.time_published | ksiDate:'short' }}</span>
```

2022-10-15 15:23 UTC, esoadamo commented on src/app/pipes/shared/ksi-date.pipe.ts
> +  transform(value: string, ...args: any[]): string | null {
Navrhuji použít raději `never` než `any` - `any` totiž ničí typovou kontrolu, kdežto `never` říká, že nám osobně nezáleží na tom, co tam je (a kdybychom to chtěli někdy použít, tak nás to upozorní, že neznáme typ)
```suggestion
  transform(value: string, ...args: never[]): string | null {
```

2022-10-19 00:28 UTC, danyroza commented
Snad by nyní mělo být vše korektní 😄

2022-10-21 11:28 UTC, esoadamo approved these changes
Je to perfektní, díky!

2022-10-21 11:29 UTC, merged